### PR TITLE
Add 3NJW-onlyrequired.mmtf example

### LINKED ISSUE #26: add a test file without any optional fields
For testing robustness of parsers, it would be useful to have a file without the optional fields (but positive number of atoms, unlike [empty-numModels1.mmtf](https://github.com/rcsb/mmtf/blob/master/test-suite/mmtf/empty-numModels1.mmtf) which has zero atoms).

I'm currently using http://pymol.org/tmp/3NJW-onlyrequired.mmtf where I simply stripped out the optional fields and adjusted the `numBonds` fields.

### PR DESCRIPTION
**Pull request by speleo3**
**3NJW** with all optional fields removed.

A file like this should help testing downstream software to comply with the spec and not fail if optional fields are missing. Example: https://github.com/MDAnalysis/mdanalysis/issues/2193

Closes #26

### CODE REVIEW

**Comment by speleo3** [comment]
File was created with this script:
```python
import struct
import msgpack

pdbid = '3NJW'

optionalkeys = '''unitCell spaceGroup structureId title depositionDate
releaseDate ncsOperatorList bioAssemblyList entityList experimentalMethods
resolution rFree rWork bondAtomList bondOrderList bFactorList atomIdList
altLocList occupancyList secStructList insCodeList sequenceIndexList
chainNameList
'''.split()

with open(pdbid + '.mmtf', 'rb') as f:
    d = msgpack.unpack(f, encoding='utf-8')

if 'bondOrderList' in d:
    n = struct.unpack('>i', d['bondOrderList'][4:8])[0]
    d['numBonds'] -= n

for key in optionalkeys:
    d.pop(key, None)

with open(pdbid + '-onlyrequired.mmtf', 'wb') as f:
    msgpack.pack(d, f, use_bin_type=True)
```

**Review by josemduarte — APPROVED** [review]
Looks good to me, thanks!

**Comment by speleo3** [comment]
Any reason why this hasn't been merged yet?

**Comment by speleo3** [comment]
thanks @josemduarte !

**Pull request merged**
